

procedure IniALLASettings;
begin
	Ini := TMemIniFile.Create(ScriptsPath + 'ALLA.ini');
	defaultOutputPlugin := Ini.ReadString('Defaults', 'OutputPlugin', 'Automated Leveled List Addition.esp');
	if not ContainsText(defaultOutputPlugin, '.esp') then defaultOutputPlugin := defaultOutputPlugin + '.esp';
	Ini.WriteString('Defaults', 'OutputPlugin', DefaultOutputPlugin);
	defaultGenerateEnchantedVersions := Ini.ReadBool('Defaults', 'GenerateEnchanted', false);
	Ini.WriteBool('Defaults', 'GenerateEnchanted', defaultGenerateEnchantedVersions);
	defaultReplaceInLeveledList := Ini.ReadBool('Defaults', 'ReplaceInLL', true);
	Ini.WriteBool('defaults', 'ReplaceInLL', defaultReplaceInLeveledList);
	defaultAllowDisenchanting := Ini.ReadBool('Defaults', 'Disenchant', true);
	Ini.WriteBool('Defaults', 'Disenchant', defaultAllowDisenchanting);
	defaultBreakdownEnchanted := Ini.ReadBool('defaults', 'BreakdownEnchanted', true);
	Ini.WriteBool('Defaults', 'BreakdownEnchanted', defaultBreakdownEnchanted);
	DefaultBreakdownDaedric := Ini.ReadBool('Defaults', 'BreakdownDaedric', true);
	Ini.WriteBool('Defaults', 'BreakdownDaedric', defaultBreakdownDaedric);
	DefaultBreakdownDLC := Ini.ReadBool('Defaults', 'BreakdownDLC', true);
	Ini.WriteBool('Defaults', 'BreakdownDLC', defaultBreakdownDLC);
	defaultGenerateRecipes := Ini.ReadBool('Defaults', 'GenerateCrafting', true);
	Ini.WriteBool('Defaults', 'GenerateCrafting', defaultGenerateRecipes);
	defaultChanceBoolean := Ini.ReadBool('Defaults', 'defaultChanceBoolean', true);
	Ini.WriteBool('Defaults', 'defaultChanceBoolean', defaultChanceBoolean);
	defaultAutoDetect := Ini.ReadBool('Defaults', 'defaultAutoDetect', true);
	Ini.WriteBool('Defaults', 'defaultAutoDetect', defaultAutoDetect);
	defaultBreakdown := Ini.ReadBool('Defaults', 'defaultBreakdown', true);
	Ini.WriteBool('Defaults', 'defaultBreakdown', defaultBreakdown);
	defaultOutfitSet := Ini.ReadBool('Defaults', 'defaultOutfitSet', False);
	Ini.WriteBool('Defaults', 'defaultOutfitSet', defaultOutfitSet);
	defaultCrafting := Ini.ReadBool('Defaults', 'defaultCrafting', true);
	Ini.WriteBool('Defaults', 'defaultCrafting', defaultCrafting);
	defaultTemper := Ini.ReadBool('Defaults', 'defaultTemper', true);
	Ini.WriteBool('Defaults', 'defaultTemper', defaultTemper);
	defaultChanceMultiplier := Ini.ReadInteger('Defaults', 'defaultChanceMultiplier', 10);
	Ini.WriteInteger('Defaults', 'defaultChanceMultiplier', defaultChanceMultiplier);
	defaultEnchMultiplier := Ini.ReadInteger('Defaults', 'defaultEnchMultiplier', 100);
	Ini.WriteInteger('Defaults', 'defaultEnchMultiplier', defaultEnchMultiplier);
	defaultItemTier01 := Ini.ReadInteger('Defaults', 'defaultItemTier01', 1);
	Ini.WriteInteger('Defaults', 'defaultItemTier01', defaultItemTier01);
	defaultItemTier02 := Ini.ReadInteger('Defaults', 'defaultItemTier02', 10);
	Ini.WriteInteger('Defaults', 'defaultItemTier02', defaultItemTier02);
	defaultItemTier03 := Ini.ReadInteger('Defaults', 'defaultItemTier03', 20);
	Ini.WriteInteger('Defaults', 'defaultItemTier03', defaultItemTier03);
	defaultItemTier04 := Ini.ReadInteger('Defaults', 'defaultItemTier04', 30);
	Ini.WriteInteger('Defaults', 'defaultItemTier04', defaultItemTier04);
	defaultItemTier05 := Ini.ReadInteger('Defaults', 'defaultItemTier05', 35);
	Ini.WriteInteger('Defaults', 'defaultItemTier05', defaultItemTier05);
	defaultItemTier06 := Ini.ReadInteger('Defaults', 'defaultItemTier06', 40);
	Ini.WriteInteger('Defaults', 'defaultItemTier06', defaultItemTier06);
	defaultTemperLight := Ini.ReadInteger('Defaults', 'defaultTemperLight', 1);
	Ini.WriteInteger('Defaults', 'defaultTemperLight', defaultTemperLight);
	defaultTemperHeavy := Ini.ReadInteger('Defaults', 'defaultTemperHeavy', 2);
	Ini.WriteInteger('Defaults', 'defaultTemperHeavy', defaultTemperHeavy);
	ProcessTime := Ini.ReadBool('Defaults', 'ProcessTime', false);
	Ini.WriteBool('Defaults', 'ProcessTime', ProcessTime);
	Constant := Ini.ReadBool('Defaults', 'Constant', true);
	Ini.WriteBool('Defaults', 'Constant', Constant);
	SetObject('GenerateEnchantedVersions', defaultGenerateEnchantedVersions, slGlobal);
	SetObject('ReplaceInLeveledList', defaultReplaceInLeveledList, slGlobal);
	SetObject('AllowDisenchanting', defaultAllowDisenchanting, slGlobal);
	SetObject('BreakdownEnchanted', defaultBreakdownEnchanted, slGlobal);	
	SetObject('ChanceMultiplier', defaultChanceMultiplier, slGlobal);	
	SetObject('BreakdownDaedric', defaultBreakdownDaedric, slGlobal);	
	SetObject('GenerateRecipes', defaultGenerateRecipes, slGlobal);	
	SetObject('EnchMultiplier', defaultEnchMultiplier, slGlobal);
	SetObject('AddtoLeveledList', defaultAutoDetect, slGlobal);
	SetObject('ChanceBoolean', defaultChanceBoolean, slGlobal);	
	SetObject('BreakdownDLC', defaultBreakdownDLC, slGlobal);
	SetObject('TemperLight', defaultTemperLight, slGlobal);
	SetObject('TemperHeavy', defaultTemperHeavy, slGlobal);
	SetObject('ItemTier01', defaultItemTier01, slGlobal);
	SetObject('ItemTier02', defaultItemTier02, slGlobal);
	SetObject('ItemTier03', defaultItemTier03, slGlobal);
	SetObject('ItemTier04', defaultItemTier04, slGlobal);
	SetObject('ItemTier05', defaultItemTier05, slGlobal);
	SetObject('ItemTier06', defaultItemTier06, slGlobal);
	SetObject('Breakdown', defaultBreakdown, slGlobal);
	SetObject('Crafting', defaultCrafting, slGlobal);
	SetObject('Temper', defaultTemper, slGlobal);
	Ini.UpdateFile;
end;